"""initial_schema

初始迁移——基于当前数据库结构自动生成。
⚠ downgrade 会删除所有表，实际使用中不应执行。

Revision ID: 35f5f2ff8a03
Revises:
Create Date: 2026-06-01 21:21:52.106763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35f5f2ff8a03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bagong_gua', 'code',
               existing_type=mysql.VARCHAR(length=6),
               comment=None,
               existing_comment='卦代码',
               existing_nullable=False)
    op.alter_column('bagong_gua', 'name',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='卦名',
               existing_nullable=False)
    op.alter_column('bagong_gua', 'palace',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='卦宫',
               existing_nullable=False)
    op.alter_column('bagong_gua', 'element',
               existing_type=mysql.VARCHAR(length=5),
               comment=None,
               existing_comment='五行',
               existing_nullable=False)
    op.alter_column('bagong_gua', 'palace_type',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='宫位类型',
               existing_nullable=False)
    op.drop_table_comment(
        'bagong_gua',
        existing_comment='八宫卦序表',
        schema=None
    )
    op.alter_column('futures_info', 'futures_code',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='期货代码',
               existing_nullable=False)
    op.alter_column('futures_info', 'futures_name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='期货名称',
               existing_nullable=False)
    op.alter_column('futures_info', 'exchange',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='交易所',
               existing_nullable=True)
    op.alter_column('futures_info', 'night_session',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='交易时段类型：无/短(23:00)/长(02:30)/外盘(24h)',
               existing_nullable=True)
    op.alter_column('futures_info', 'data_source',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='数据来源',
               existing_nullable=True)
    op.alter_column('futures_info', 'tag_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联标签ID',
               existing_nullable=True)
    op.alter_column('futures_info', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('futures_info_ibfk_1'), 'futures_info', type_='foreignkey')
    op.create_foreign_key(None, 'futures_info', 'tag', ['tag_id'], ['id'])
    op.drop_table_comment(
        'futures_info',
        existing_comment='期货信息表',
        schema=None
    )
    op.alter_column('futures_minute_kline', 'futures_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='期货ID',
               existing_nullable=False)
    op.alter_column('futures_minute_kline', 'trade_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='交易时间（精确到分钟，含夜盘跨天时间）',
               existing_nullable=False)
    op.alter_column('futures_minute_kline', 'open_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='开盘价',
               existing_nullable=True)
    op.alter_column('futures_minute_kline', 'high_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='最高价',
               existing_nullable=True)
    op.alter_column('futures_minute_kline', 'low_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='最低价',
               existing_nullable=True)
    op.alter_column('futures_minute_kline', 'close_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='收盘价',
               existing_nullable=True)
    op.alter_column('futures_minute_kline', 'volume',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='成交量',
               existing_nullable=True)
    op.drop_index(op.f('idx_futures_time'), table_name='futures_minute_kline')
    op.drop_constraint(op.f('futures_minute_kline_ibfk_1'), 'futures_minute_kline', type_='foreignkey')
    op.create_foreign_key(None, 'futures_minute_kline', 'futures_info', ['futures_id'], ['id'])
    op.drop_table_comment(
        'futures_minute_kline',
        existing_comment='期货分钟K线表',
        schema=None
    )
    op.alter_column('guaci', 'code',
               existing_type=mysql.VARCHAR(length=6),
               comment=None,
               existing_comment='卦代码',
               existing_nullable=False)
    op.alter_column('guaci', 'gua_ci',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='卦辞',
               existing_nullable=True)
    op.alter_column('guaci', 'tuan_zhuan',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='彖传',
               existing_nullable=True)
    op.alter_column('guaci', 'xiang_zhuan',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='象传',
               existing_nullable=True)
    op.alter_column('guaci', 'yao_ci',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='爻辞（JSON格式）',
               existing_nullable=True)
    op.alter_column('guaci', 'wenyan',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='文言（仅乾坤二卦）',
               existing_nullable=True)
    op.alter_column('guaci', 'yong',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='用九/用六（仅乾坤二卦）',
               existing_nullable=True)
    op.drop_table_comment(
        'guaci',
        existing_comment='卦爻辞表',
        schema=None
    )
    op.alter_column('guali', 'zhanwen_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='占问时间',
               existing_nullable=False)
    op.alter_column('guali', 'zhanwen_shiyou',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='占问事由',
               existing_nullable=True)
    op.alter_column('guali', 'zhanduan',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='占断内容',
               existing_nullable=True)
    op.alter_column('guali', 'ben_code',
               existing_type=mysql.VARCHAR(length=6),
               comment=None,
               existing_comment='本卦代码',
               existing_nullable=False)
    op.alter_column('guali', 'yao_bian_code',
               existing_type=mysql.VARCHAR(length=6),
               comment=None,
               existing_comment='爻变代码',
               existing_nullable=False,
               existing_server_default=sa.text("'000000'"))
    op.alter_column('guali', 'zhi_code',
               existing_type=mysql.VARCHAR(length=6),
               comment=None,
               existing_comment='之卦代码',
               existing_nullable=False,
               existing_server_default=sa.text("'000000'"))
    op.drop_index(op.f('idx_ben_code'), table_name='guali')
    op.drop_index(op.f('idx_zhanwen_shiyou'), table_name='guali', mysql_length={'zhanwen_shiyou': 100})
    op.drop_index(op.f('idx_zhi_code'), table_name='guali')
    op.drop_table_comment(
        'guali',
        existing_comment='卦例主表',
        schema=None
    )
    op.alter_column('guali_gua', 'guali_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联卦例ID',
               existing_nullable=False)
    op.alter_column('guali_gua', 'ben_inner_code',
               existing_type=mysql.VARCHAR(length=3),
               comment=None,
               existing_comment='本卦内卦代码',
               existing_nullable=True)
    op.alter_column('guali_gua', 'ben_outer_code',
               existing_type=mysql.VARCHAR(length=3),
               comment=None,
               existing_comment='本卦外卦代码',
               existing_nullable=True)
    op.alter_column('guali_gua', 'ben_palace',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='本卦卦宫',
               existing_nullable=True)
    op.alter_column('guali_gua', 'ben_palace_type',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='本卦宫位',
               existing_nullable=True)
    op.alter_column('guali_gua', 'ben_special_type',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='本卦特殊类型',
               existing_nullable=True)
    op.alter_column('guali_gua', 'zhi_inner_code',
               existing_type=mysql.VARCHAR(length=3),
               comment=None,
               existing_comment='之卦内卦代码',
               existing_nullable=True)
    op.alter_column('guali_gua', 'zhi_outer_code',
               existing_type=mysql.VARCHAR(length=3),
               comment=None,
               existing_comment='之卦外卦代码',
               existing_nullable=True)
    op.alter_column('guali_gua', 'zhi_palace',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='之卦卦宫',
               existing_nullable=True)
    op.alter_column('guali_gua', 'zhi_palace_type',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='之卦宫位',
               existing_nullable=True)
    op.alter_column('guali_gua', 'zhi_special_type',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='之卦特殊类型',
               existing_nullable=True)
    op.alter_column('guali_gua', 'fan_yin_yimao',
               existing_type=mysql.VARCHAR(length=4),
               comment=None,
               existing_comment='易冒反吟',
               existing_nullable=True)
    op.alter_column('guali_gua', 'fan_yin_yaobian',
               existing_type=mysql.VARCHAR(length=4),
               comment=None,
               existing_comment='爻变反吟',
               existing_nullable=True)
    op.alter_column('guali_gua', 'fu_yin',
               existing_type=mysql.VARCHAR(length=4),
               comment=None,
               existing_comment='伏吟',
               existing_nullable=True)
    op.drop_index(op.f('idx_ben_palace'), table_name='guali_gua')
    op.drop_index(op.f('idx_ben_palace_type'), table_name='guali_gua')
    op.drop_index(op.f('idx_ben_special_type'), table_name='guali_gua')
    op.drop_index(op.f('idx_fan_yin'), table_name='guali_gua')
    op.drop_index(op.f('idx_gua_guali_id'), table_name='guali_gua')
    op.drop_index(op.f('idx_zhi_palace'), table_name='guali_gua')
    op.drop_index(op.f('idx_zhi_palace_type'), table_name='guali_gua')
    op.drop_index(op.f('idx_zhi_special_type'), table_name='guali_gua')
    op.drop_index(op.f('uk_guali_id'), table_name='guali_gua')
    op.drop_constraint(op.f('guali_gua_ibfk_1'), 'guali_gua', type_='foreignkey')
    op.create_foreign_key(None, 'guali_gua', 'guali', ['guali_id'], ['id'])
    op.drop_table_comment(
        'guali_gua',
        existing_comment='卦类扩展表（1行/卦例，14字段）',
        schema=None
    )
    op.alter_column('guali_shensha', 'guali_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联卦例ID',
               existing_nullable=False)
    op.alter_column('guali_shensha', 'gan_lu',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='干禄地支',
               existing_nullable=True)
    op.alter_column('guali_shensha', 'yi_ma',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='驿马地支',
               existing_nullable=True)
    op.alter_column('guali_shensha', 'yang_ren',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='羊刃地支',
               existing_nullable=True)
    op.alter_column('guali_shensha', 'tao_hua',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='桃花地支',
               existing_nullable=True)
    op.alter_column('guali_shensha', 'zai_sha',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='灾煞地支',
               existing_nullable=True)
    op.alter_column('guali_shensha', 'jie_sha',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='劫煞地支',
               existing_nullable=True)
    op.alter_column('guali_shensha', 'yimao_is_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_dai_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_is_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_dai_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_is_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_dai_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_is_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_dai_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_is_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_dai_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_is_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_dai_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_is_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_dai_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_is_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_dai_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_is_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_dai_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_is_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_dai_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_is_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_dai_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_is_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_dai_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_is_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_dai_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_is_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_dai_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_is_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_dai_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_is_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_dai_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_is_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_dai_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_is_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_dai_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_is_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_dai_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_is_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_dai_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_is_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_dai_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_is_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_dai_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_is_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_dai_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_is_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='是劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_dai_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='带劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.drop_index(op.f('idx_gan_lu'), table_name='guali_shensha')
    op.drop_index(op.f('idx_jie_sha'), table_name='guali_shensha')
    op.drop_index(op.f('idx_shensha_guali_id'), table_name='guali_shensha')
    op.drop_index(op.f('idx_tao_hua'), table_name='guali_shensha')
    op.drop_index(op.f('idx_yang_ren'), table_name='guali_shensha')
    op.drop_index(op.f('idx_yi_ma'), table_name='guali_shensha')
    op.drop_index(op.f('idx_zai_sha'), table_name='guali_shensha')
    op.drop_index(op.f('uk_guali_id'), table_name='guali_shensha')
    op.drop_constraint(op.f('guali_shensha_ibfk_1'), 'guali_shensha', type_='foreignkey')
    op.create_foreign_key(None, 'guali_shensha', 'guali', ['guali_id'], ['id'])
    op.drop_table_comment(
        'guali_shensha',
        existing_comment='神煞扩展表（1行/卦例，37字段）',
        schema=None
    )
    op.drop_constraint(op.f('guali_tag_ibfk_2'), 'guali_tag', type_='foreignkey')
    op.drop_constraint(op.f('guali_tag_ibfk_1'), 'guali_tag', type_='foreignkey')
    op.create_foreign_key(None, 'guali_tag', 'guali', ['guali_id'], ['id'])
    op.create_foreign_key(None, 'guali_tag', 'tag', ['tag_id'], ['id'])
    op.drop_table_comment(
        'guali_tag',
        existing_comment='卦例-标签关联表',
        schema=None
    )
    op.alter_column('guali_time', 'guali_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联卦例ID',
               existing_nullable=False)
    op.alter_column('guali_time', 'year_pillar',
               existing_type=mysql.VARCHAR(length=4),
               comment=None,
               existing_comment='年柱',
               existing_nullable=True)
    op.alter_column('guali_time', 'year_gan',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='年干',
               existing_nullable=True)
    op.alter_column('guali_time', 'year_zhi',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='年支',
               existing_nullable=True)
    op.alter_column('guali_time', 'month_pillar',
               existing_type=mysql.VARCHAR(length=4),
               comment=None,
               existing_comment='月柱',
               existing_nullable=True)
    op.alter_column('guali_time', 'month_gan',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='月干',
               existing_nullable=True)
    op.alter_column('guali_time', 'month_zhi',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='月支',
               existing_nullable=True)
    op.alter_column('guali_time', 'day_pillar',
               existing_type=mysql.VARCHAR(length=4),
               comment=None,
               existing_comment='日柱',
               existing_nullable=True)
    op.alter_column('guali_time', 'day_gan',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='日干',
               existing_nullable=True)
    op.alter_column('guali_time', 'day_zhi',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='日支',
               existing_nullable=True)
    op.alter_column('guali_time', 'xun_kong',
               existing_type=mysql.VARCHAR(length=4),
               comment=None,
               existing_comment='旬空',
               existing_nullable=True)
    op.drop_index(op.f('idx_day_gan'), table_name='guali_time')
    op.drop_index(op.f('idx_day_zhi'), table_name='guali_time')
    op.drop_index(op.f('idx_month_zhi'), table_name='guali_time')
    op.drop_index(op.f('idx_time_guali_id'), table_name='guali_time')
    op.drop_index(op.f('idx_xun_kong'), table_name='guali_time')
    op.drop_index(op.f('idx_year_zhi'), table_name='guali_time')
    op.drop_index(op.f('uk_guali_id'), table_name='guali_time')
    op.drop_constraint(op.f('guali_time_ibfk_1'), 'guali_time', type_='foreignkey')
    op.create_foreign_key(None, 'guali_time', 'guali', ['guali_id'], ['id'])
    op.drop_table_comment(
        'guali_time',
        existing_comment='时间扩展表（1行/卦例）',
        schema=None
    )
    op.alter_column('guali_yao', 'guali_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联卦例ID',
               existing_nullable=False)
    op.alter_column('guali_yao', 'yao_position',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               comment=None,
               existing_comment='爻位（1-6）',
               existing_nullable=False)
    op.alter_column('guali_yao', 'liushen',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='六神',
               existing_nullable=True)
    op.alter_column('guali_yao', 'yimao_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='易冒伏神六亲',
               existing_nullable=True)
    op.alter_column('guali_yao', 'yimao_dizhi',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='易冒伏神地支',
               existing_nullable=True)
    op.alter_column('guali_yao', 'zengshan_exists',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment=None,
               existing_comment='是否存在增删伏神',
               existing_server_default=sa.text("'0'"))
    op.alter_column('guali_yao', 'zengshan_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='增删伏神六亲',
               existing_nullable=True)
    op.alter_column('guali_yao', 'zengshan_dizhi',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='增删伏神地支',
               existing_nullable=True)
    op.alter_column('guali_yao', 'ben_yao_type',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='本卦爻类型（阴/阳）',
               existing_nullable=True)
    op.alter_column('guali_yao', 'ben_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='本卦六亲',
               existing_nullable=True)
    op.alter_column('guali_yao', 'ben_tiangan',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='本卦天干',
               existing_nullable=True)
    op.alter_column('guali_yao', 'ben_dizhi',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='本卦地支',
               existing_nullable=True)
    op.alter_column('guali_yao', 'ben_shi_ying',
               existing_type=mysql.VARCHAR(length=4),
               comment=None,
               existing_comment='本卦世应',
               existing_nullable=True)
    op.alter_column('guali_yao', 'is_dong',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment=None,
               existing_comment='是否动爻',
               existing_server_default=sa.text("'0'"))
    op.alter_column('guali_yao', 'is_an_dong',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment=None,
               existing_comment='是否暗动',
               existing_server_default=sa.text("'0'"))
    op.alter_column('guali_yao', 'zhi_yao_type',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='之卦爻类型（阴/阳）',
               existing_nullable=True)
    op.alter_column('guali_yao', 'zhi_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='之卦六亲',
               existing_nullable=True)
    op.alter_column('guali_yao', 'zhi_tiangan',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='之卦天干',
               existing_nullable=True)
    op.alter_column('guali_yao', 'zhi_dizhi',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='之卦地支',
               existing_nullable=True)
    op.alter_column('guali_yao', 'zhi_shi_ying',
               existing_type=mysql.VARCHAR(length=4),
               comment=None,
               existing_comment='之卦世应',
               existing_nullable=True)
    op.drop_index(op.f('idx_ben_dizhi'), table_name='guali_yao')
    op.drop_index(op.f('idx_ben_liuqin'), table_name='guali_yao')
    op.drop_index(op.f('idx_ben_shi_ying'), table_name='guali_yao')
    op.drop_index(op.f('idx_ben_yao_type'), table_name='guali_yao')
    op.drop_index(op.f('idx_is_an_dong'), table_name='guali_yao')
    op.drop_index(op.f('idx_is_dong'), table_name='guali_yao')
    op.drop_index(op.f('idx_liushen'), table_name='guali_yao')
    op.drop_index(op.f('idx_yao_guali_id'), table_name='guali_yao')
    op.drop_index(op.f('idx_yimao_dizhi'), table_name='guali_yao')
    op.drop_index(op.f('idx_yimao_liuqin'), table_name='guali_yao')
    op.drop_index(op.f('idx_zengshan_dizhi'), table_name='guali_yao')
    op.drop_index(op.f('idx_zengshan_exists'), table_name='guali_yao')
    op.drop_index(op.f('idx_zengshan_liuqin'), table_name='guali_yao')
    op.drop_index(op.f('idx_zhi_dizhi'), table_name='guali_yao')
    op.drop_index(op.f('idx_zhi_liuqin'), table_name='guali_yao')
    op.drop_index(op.f('uk_guali_yao'), table_name='guali_yao')
    op.drop_constraint(op.f('guali_yao_ibfk_1'), 'guali_yao', type_='foreignkey')
    op.create_foreign_key(None, 'guali_yao', 'guali', ['guali_id'], ['id'])
    op.drop_table_comment(
        'guali_yao',
        existing_comment='爻类扩展表（6行/卦例，20字段）',
        schema=None
    )
    op.alter_column('static_fushen_yimao', 'code',
               existing_type=mysql.VARCHAR(length=6),
               comment=None,
               existing_comment='卦代码',
               existing_nullable=False)
    op.alter_column('static_fushen_yimao', 'yao_index',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='爻位',
               existing_nullable=False)
    op.alter_column('static_fushen_yimao', 'fushen_dizhi',
               existing_type=mysql.VARCHAR(length=1),
               comment=None,
               existing_comment='伏神地支',
               existing_nullable=False)
    op.alter_column('static_fushen_yimao', 'fushen_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='伏神六亲',
               existing_nullable=False)
    op.drop_constraint(op.f('static_fushen_yimao_ibfk_1'), 'static_fushen_yimao', type_='foreignkey')
    op.create_foreign_key(None, 'static_fushen_yimao', 'bagong_gua', ['code'], ['code'])
    op.drop_table_comment(
        'static_fushen_yimao',
        existing_comment='64卦×6爻=384条记录',
        schema=None
    )
    op.alter_column('static_fushen_zengshan', 'code',
               existing_type=mysql.VARCHAR(length=6),
               comment=None,
               existing_comment='卦代码',
               existing_nullable=False)
    op.alter_column('static_fushen_zengshan', 'yao_index',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='爻位（伏神伏在此爻位下）',
               existing_nullable=False)
    op.alter_column('static_fushen_zengshan', 'missing_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='缺失的六亲',
               existing_nullable=False)
    op.alter_column('static_fushen_zengshan', 'fushen_dizhi',
               existing_type=mysql.VARCHAR(length=1),
               comment=None,
               existing_comment='伏神地支',
               existing_nullable=False)
    op.alter_column('static_fushen_zengshan', 'fushen_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='伏神六亲',
               existing_nullable=False)
    op.alter_column('static_fushen_zengshan', 'feishen_dizhi',
               existing_type=mysql.VARCHAR(length=1),
               comment=None,
               existing_comment='飞神地支',
               existing_nullable=False)
    op.alter_column('static_fushen_zengshan', 'feishen_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='飞神六亲',
               existing_nullable=False)
    op.drop_constraint(op.f('static_fushen_zengshan_ibfk_1'), 'static_fushen_zengshan', type_='foreignkey')
    op.create_foreign_key(None, 'static_fushen_zengshan', 'bagong_gua', ['code'], ['code'])
    op.drop_table_comment(
        'static_fushen_zengshan',
        existing_comment='64卦约64条记录',
        schema=None
    )
    op.alter_column('static_gua_yao_info', 'code',
               existing_type=mysql.VARCHAR(length=6),
               comment=None,
               existing_comment='卦代码',
               existing_nullable=False)
    op.alter_column('static_gua_yao_info', 'yao_index',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='爻位（1-6）',
               existing_nullable=False)
    op.alter_column('static_gua_yao_info', 'dizhi',
               existing_type=mysql.VARCHAR(length=1),
               comment=None,
               existing_comment='地支',
               existing_nullable=False)
    op.alter_column('static_gua_yao_info', 'tiangan',
               existing_type=mysql.VARCHAR(length=1),
               comment=None,
               existing_comment='天干（普通卦）',
               existing_nullable=True)
    op.alter_column('static_gua_yao_info', 'tiangan_summer',
               existing_type=mysql.VARCHAR(length=1),
               comment=None,
               existing_comment='天干-夏至后（乾坤相关卦）',
               existing_nullable=True)
    op.alter_column('static_gua_yao_info', 'tiangan_winter',
               existing_type=mysql.VARCHAR(length=1),
               comment=None,
               existing_comment='天干-冬至后（乾坤相关卦）',
               existing_nullable=True)
    op.alter_column('static_gua_yao_info', 'liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='六亲',
               existing_nullable=False)
    op.drop_constraint(op.f('static_gua_yao_info_ibfk_1'), 'static_gua_yao_info', type_='foreignkey')
    op.create_foreign_key(None, 'static_gua_yao_info', 'bagong_gua', ['code'], ['code'])
    op.drop_table_comment(
        'static_gua_yao_info',
        existing_comment='64卦×6爻=384条记录',
        schema=None
    )
    op.alter_column('stock_day_kline', 'stock_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='股票ID',
               existing_nullable=False)
    op.alter_column('stock_day_kline', 'trade_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
    op.alter_column('stock_day_kline', 'open_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='开盘价',
               existing_nullable=True)
    op.alter_column('stock_day_kline', 'high_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='最高价',
               existing_nullable=True)
    op.alter_column('stock_day_kline', 'low_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='最低价',
               existing_nullable=True)
    op.alter_column('stock_day_kline', 'close_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='收盘价',
               existing_nullable=True)
    op.alter_column('stock_day_kline', 'volume',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='成交量',
               existing_nullable=True)
    op.drop_index(op.f('uk_stock_date'), table_name='stock_day_kline')
    op.drop_constraint(op.f('stock_day_kline_ibfk_1'), 'stock_day_kline', type_='foreignkey')
    op.create_foreign_key(None, 'stock_day_kline', 'stock_info', ['stock_id'], ['id'])
    op.drop_table_comment(
        'stock_day_kline',
        existing_comment='股票日K数据表',
        schema=None
    )
    op.alter_column('stock_info', 'stock_code',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='股票代码',
               existing_nullable=False)
    op.alter_column('stock_info', 'stock_name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='股票名称',
               existing_nullable=False)
    op.alter_column('stock_info', 'exchange',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='交易所',
               existing_nullable=True)
    op.alter_column('stock_info', 'data_source',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='数据来源',
               existing_nullable=True)
    op.alter_column('stock_info', 'tag_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联标签ID',
               existing_nullable=True)
    op.alter_column('stock_info', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('stock_info_ibfk_1'), 'stock_info', type_='foreignkey')
    op.create_foreign_key(None, 'stock_info', 'tag', ['tag_id'], ['id'])
    op.drop_table_comment(
        'stock_info',
        existing_comment='股票信息表',
        schema=None
    )
    op.alter_column('stock_minute_kline', 'stock_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='股票ID',
               existing_nullable=False)
    op.alter_column('stock_minute_kline', 'trade_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='交易时间（精确到分钟）',
               existing_nullable=False)
    op.alter_column('stock_minute_kline', 'open_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='开盘价',
               existing_nullable=True)
    op.alter_column('stock_minute_kline', 'high_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='最高价',
               existing_nullable=True)
    op.alter_column('stock_minute_kline', 'low_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='最低价',
               existing_nullable=True)
    op.alter_column('stock_minute_kline', 'close_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='收盘价',
               existing_nullable=True)
    op.alter_column('stock_minute_kline', 'volume',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='成交量',
               existing_nullable=True)
    op.drop_index(op.f('idx_stock_time'), table_name='stock_minute_kline')
    op.drop_constraint(op.f('stock_minute_kline_ibfk_1'), 'stock_minute_kline', type_='foreignkey')
    op.create_foreign_key(None, 'stock_minute_kline', 'stock_info', ['stock_id'], ['id'])
    op.drop_table_comment(
        'stock_minute_kline',
        existing_comment='股票分时数据表',
        schema=None
    )
    op.alter_column('system_config', 'config_key',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='配置项名称',
               existing_nullable=False)
    op.alter_column('system_config', 'config_value',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='配置项值',
               existing_nullable=True)
    op.drop_table_comment(
        'system_config',
        existing_comment='系统配置表',
        schema=None
    )
    op.alter_column('tag', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='父标签ID',
               existing_nullable=True)
    op.alter_column('tag', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='标签名称',
               existing_nullable=False)
    op.drop_constraint(op.f('tag_ibfk_1'), 'tag', type_='foreignkey')
    op.create_foreign_key(None, 'tag', 'tag', ['parent_id'], ['id'])
    op.drop_table_comment(
        'tag',
        existing_comment='标签表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'tag',
        '标签表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('tag_ibfk_1', 'tag', type_='foreignkey')
    op.create_foreign_key(op.f('tag_ibfk_1'), 'tag', 'tag', ['parent_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tag', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment='标签名称',
               existing_nullable=False)
    op.alter_column('tag', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment='父标签ID',
               existing_nullable=True)
    op.create_table_comment(
        'system_config',
        '系统配置表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('system_config', 'config_value',
               existing_type=mysql.TEXT(),
               comment='配置项值',
               existing_nullable=True)
    op.alter_column('system_config', 'config_key',
               existing_type=mysql.VARCHAR(length=50),
               comment='配置项名称',
               existing_nullable=False)
    op.create_table_comment(
        'stock_minute_kline',
        '股票分时数据表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('stock_minute_kline_ibfk_1', 'stock_minute_kline', type_='foreignkey')
    op.create_foreign_key(op.f('stock_minute_kline_ibfk_1'), 'stock_minute_kline', 'stock_info', ['stock_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_stock_time'), 'stock_minute_kline', ['stock_id', 'trade_time'], unique=False)
    op.alter_column('stock_minute_kline', 'volume',
               existing_type=mysql.BIGINT(),
               comment='成交量',
               existing_nullable=True)
    op.alter_column('stock_minute_kline', 'close_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='收盘价',
               existing_nullable=True)
    op.alter_column('stock_minute_kline', 'low_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='最低价',
               existing_nullable=True)
    op.alter_column('stock_minute_kline', 'high_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='最高价',
               existing_nullable=True)
    op.alter_column('stock_minute_kline', 'open_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='开盘价',
               existing_nullable=True)
    op.alter_column('stock_minute_kline', 'trade_time',
               existing_type=mysql.DATETIME(),
               comment='交易时间（精确到分钟）',
               existing_nullable=False)
    op.alter_column('stock_minute_kline', 'stock_id',
               existing_type=mysql.INTEGER(),
               comment='股票ID',
               existing_nullable=False)
    op.create_table_comment(
        'stock_info',
        '股票信息表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('stock_info_ibfk_1', 'stock_info', type_='foreignkey')
    op.create_foreign_key(op.f('stock_info_ibfk_1'), 'stock_info', 'tag', ['tag_id'], ['id'], ondelete='SET NULL')
    op.alter_column('stock_info', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('stock_info', 'tag_id',
               existing_type=mysql.INTEGER(),
               comment='关联标签ID',
               existing_nullable=True)
    op.alter_column('stock_info', 'data_source',
               existing_type=mysql.VARCHAR(length=20),
               comment='数据来源',
               existing_nullable=True)
    op.alter_column('stock_info', 'exchange',
               existing_type=mysql.VARCHAR(length=20),
               comment='交易所',
               existing_nullable=True)
    op.alter_column('stock_info', 'stock_name',
               existing_type=mysql.VARCHAR(length=50),
               comment='股票名称',
               existing_nullable=False)
    op.alter_column('stock_info', 'stock_code',
               existing_type=mysql.VARCHAR(length=20),
               comment='股票代码',
               existing_nullable=False)
    op.create_table_comment(
        'stock_day_kline',
        '股票日K数据表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('stock_day_kline_ibfk_1', 'stock_day_kline', type_='foreignkey')
    op.create_foreign_key(op.f('stock_day_kline_ibfk_1'), 'stock_day_kline', 'stock_info', ['stock_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('uk_stock_date'), 'stock_day_kline', ['stock_id', 'trade_date'], unique=True)
    op.alter_column('stock_day_kline', 'volume',
               existing_type=mysql.BIGINT(),
               comment='成交量',
               existing_nullable=True)
    op.alter_column('stock_day_kline', 'close_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='收盘价',
               existing_nullable=True)
    op.alter_column('stock_day_kline', 'low_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='最低价',
               existing_nullable=True)
    op.alter_column('stock_day_kline', 'high_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='最高价',
               existing_nullable=True)
    op.alter_column('stock_day_kline', 'open_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='开盘价',
               existing_nullable=True)
    op.alter_column('stock_day_kline', 'trade_date',
               existing_type=sa.DATE(),
               comment='交易日期',
               existing_nullable=False)
    op.alter_column('stock_day_kline', 'stock_id',
               existing_type=mysql.INTEGER(),
               comment='股票ID',
               existing_nullable=False)
    op.create_table_comment(
        'static_gua_yao_info',
        '64卦×6爻=384条记录',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('static_gua_yao_info_ibfk_1', 'static_gua_yao_info', type_='foreignkey')
    op.create_foreign_key(op.f('static_gua_yao_info_ibfk_1'), 'static_gua_yao_info', 'bagong_gua', ['code'], ['code'], ondelete='CASCADE')
    op.alter_column('static_gua_yao_info', 'liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment='六亲',
               existing_nullable=False)
    op.alter_column('static_gua_yao_info', 'tiangan_winter',
               existing_type=mysql.VARCHAR(length=1),
               comment='天干-冬至后（乾坤相关卦）',
               existing_nullable=True)
    op.alter_column('static_gua_yao_info', 'tiangan_summer',
               existing_type=mysql.VARCHAR(length=1),
               comment='天干-夏至后（乾坤相关卦）',
               existing_nullable=True)
    op.alter_column('static_gua_yao_info', 'tiangan',
               existing_type=mysql.VARCHAR(length=1),
               comment='天干（普通卦）',
               existing_nullable=True)
    op.alter_column('static_gua_yao_info', 'dizhi',
               existing_type=mysql.VARCHAR(length=1),
               comment='地支',
               existing_nullable=False)
    op.alter_column('static_gua_yao_info', 'yao_index',
               existing_type=mysql.INTEGER(),
               comment='爻位（1-6）',
               existing_nullable=False)
    op.alter_column('static_gua_yao_info', 'code',
               existing_type=mysql.VARCHAR(length=6),
               comment='卦代码',
               existing_nullable=False)
    op.create_table_comment(
        'static_fushen_zengshan',
        '64卦约64条记录',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('static_fushen_zengshan_ibfk_1', 'static_fushen_zengshan', type_='foreignkey')
    op.create_foreign_key(op.f('static_fushen_zengshan_ibfk_1'), 'static_fushen_zengshan', 'bagong_gua', ['code'], ['code'], ondelete='CASCADE')
    op.alter_column('static_fushen_zengshan', 'feishen_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment='飞神六亲',
               existing_nullable=False)
    op.alter_column('static_fushen_zengshan', 'feishen_dizhi',
               existing_type=mysql.VARCHAR(length=1),
               comment='飞神地支',
               existing_nullable=False)
    op.alter_column('static_fushen_zengshan', 'fushen_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment='伏神六亲',
               existing_nullable=False)
    op.alter_column('static_fushen_zengshan', 'fushen_dizhi',
               existing_type=mysql.VARCHAR(length=1),
               comment='伏神地支',
               existing_nullable=False)
    op.alter_column('static_fushen_zengshan', 'missing_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment='缺失的六亲',
               existing_nullable=False)
    op.alter_column('static_fushen_zengshan', 'yao_index',
               existing_type=mysql.INTEGER(),
               comment='爻位（伏神伏在此爻位下）',
               existing_nullable=False)
    op.alter_column('static_fushen_zengshan', 'code',
               existing_type=mysql.VARCHAR(length=6),
               comment='卦代码',
               existing_nullable=False)
    op.create_table_comment(
        'static_fushen_yimao',
        '64卦×6爻=384条记录',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('static_fushen_yimao_ibfk_1', 'static_fushen_yimao', type_='foreignkey')
    op.create_foreign_key(op.f('static_fushen_yimao_ibfk_1'), 'static_fushen_yimao', 'bagong_gua', ['code'], ['code'], ondelete='CASCADE')
    op.alter_column('static_fushen_yimao', 'fushen_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment='伏神六亲',
               existing_nullable=False)
    op.alter_column('static_fushen_yimao', 'fushen_dizhi',
               existing_type=mysql.VARCHAR(length=1),
               comment='伏神地支',
               existing_nullable=False)
    op.alter_column('static_fushen_yimao', 'yao_index',
               existing_type=mysql.INTEGER(),
               comment='爻位',
               existing_nullable=False)
    op.alter_column('static_fushen_yimao', 'code',
               existing_type=mysql.VARCHAR(length=6),
               comment='卦代码',
               existing_nullable=False)
    op.create_table_comment(
        'guali_yao',
        '爻类扩展表（6行/卦例，20字段）',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('guali_yao_ibfk_1', 'guali_yao', type_='foreignkey')
    op.create_foreign_key(op.f('guali_yao_ibfk_1'), 'guali_yao', 'guali', ['guali_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('uk_guali_yao'), 'guali_yao', ['guali_id', 'yao_position'], unique=True)
    op.create_index(op.f('idx_zhi_liuqin'), 'guali_yao', ['zhi_liuqin'], unique=False)
    op.create_index(op.f('idx_zhi_dizhi'), 'guali_yao', ['zhi_dizhi'], unique=False)
    op.create_index(op.f('idx_zengshan_liuqin'), 'guali_yao', ['zengshan_liuqin'], unique=False)
    op.create_index(op.f('idx_zengshan_exists'), 'guali_yao', ['zengshan_exists'], unique=False)
    op.create_index(op.f('idx_zengshan_dizhi'), 'guali_yao', ['zengshan_dizhi'], unique=False)
    op.create_index(op.f('idx_yimao_liuqin'), 'guali_yao', ['yimao_liuqin'], unique=False)
    op.create_index(op.f('idx_yimao_dizhi'), 'guali_yao', ['yimao_dizhi'], unique=False)
    op.create_index(op.f('idx_yao_guali_id'), 'guali_yao', ['guali_id'], unique=False)
    op.create_index(op.f('idx_liushen'), 'guali_yao', ['liushen'], unique=False)
    op.create_index(op.f('idx_is_dong'), 'guali_yao', ['is_dong'], unique=False)
    op.create_index(op.f('idx_is_an_dong'), 'guali_yao', ['is_an_dong'], unique=False)
    op.create_index(op.f('idx_ben_yao_type'), 'guali_yao', ['ben_yao_type'], unique=False)
    op.create_index(op.f('idx_ben_shi_ying'), 'guali_yao', ['ben_shi_ying'], unique=False)
    op.create_index(op.f('idx_ben_liuqin'), 'guali_yao', ['ben_liuqin'], unique=False)
    op.create_index(op.f('idx_ben_dizhi'), 'guali_yao', ['ben_dizhi'], unique=False)
    op.alter_column('guali_yao', 'zhi_shi_ying',
               existing_type=mysql.VARCHAR(length=4),
               comment='之卦世应',
               existing_nullable=True)
    op.alter_column('guali_yao', 'zhi_dizhi',
               existing_type=mysql.VARCHAR(length=2),
               comment='之卦地支',
               existing_nullable=True)
    op.alter_column('guali_yao', 'zhi_tiangan',
               existing_type=mysql.VARCHAR(length=2),
               comment='之卦天干',
               existing_nullable=True)
    op.alter_column('guali_yao', 'zhi_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment='之卦六亲',
               existing_nullable=True)
    op.alter_column('guali_yao', 'zhi_yao_type',
               existing_type=mysql.VARCHAR(length=2),
               comment='之卦爻类型（阴/阳）',
               existing_nullable=True)
    op.alter_column('guali_yao', 'is_an_dong',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='是否暗动',
               existing_server_default=sa.text("'0'"))
    op.alter_column('guali_yao', 'is_dong',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='是否动爻',
               existing_server_default=sa.text("'0'"))
    op.alter_column('guali_yao', 'ben_shi_ying',
               existing_type=mysql.VARCHAR(length=4),
               comment='本卦世应',
               existing_nullable=True)
    op.alter_column('guali_yao', 'ben_dizhi',
               existing_type=mysql.VARCHAR(length=2),
               comment='本卦地支',
               existing_nullable=True)
    op.alter_column('guali_yao', 'ben_tiangan',
               existing_type=mysql.VARCHAR(length=2),
               comment='本卦天干',
               existing_nullable=True)
    op.alter_column('guali_yao', 'ben_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment='本卦六亲',
               existing_nullable=True)
    op.alter_column('guali_yao', 'ben_yao_type',
               existing_type=mysql.VARCHAR(length=2),
               comment='本卦爻类型（阴/阳）',
               existing_nullable=True)
    op.alter_column('guali_yao', 'zengshan_dizhi',
               existing_type=mysql.VARCHAR(length=2),
               comment='增删伏神地支',
               existing_nullable=True)
    op.alter_column('guali_yao', 'zengshan_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment='增删伏神六亲',
               existing_nullable=True)
    op.alter_column('guali_yao', 'zengshan_exists',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='是否存在增删伏神',
               existing_server_default=sa.text("'0'"))
    op.alter_column('guali_yao', 'yimao_dizhi',
               existing_type=mysql.VARCHAR(length=2),
               comment='易冒伏神地支',
               existing_nullable=True)
    op.alter_column('guali_yao', 'yimao_liuqin',
               existing_type=mysql.VARCHAR(length=10),
               comment='易冒伏神六亲',
               existing_nullable=True)
    op.alter_column('guali_yao', 'liushen',
               existing_type=mysql.VARCHAR(length=10),
               comment='六神',
               existing_nullable=True)
    op.alter_column('guali_yao', 'yao_position',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               comment='爻位（1-6）',
               existing_nullable=False)
    op.alter_column('guali_yao', 'guali_id',
               existing_type=mysql.INTEGER(),
               comment='关联卦例ID',
               existing_nullable=False)
    op.create_table_comment(
        'guali_time',
        '时间扩展表（1行/卦例）',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('guali_time_ibfk_1', 'guali_time', type_='foreignkey')
    op.create_foreign_key(op.f('guali_time_ibfk_1'), 'guali_time', 'guali', ['guali_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('uk_guali_id'), 'guali_time', ['guali_id'], unique=True)
    op.create_index(op.f('idx_year_zhi'), 'guali_time', ['year_zhi'], unique=False)
    op.create_index(op.f('idx_xun_kong'), 'guali_time', ['xun_kong'], unique=False)
    op.create_index(op.f('idx_time_guali_id'), 'guali_time', ['guali_id'], unique=False)
    op.create_index(op.f('idx_month_zhi'), 'guali_time', ['month_zhi'], unique=False)
    op.create_index(op.f('idx_day_zhi'), 'guali_time', ['day_zhi'], unique=False)
    op.create_index(op.f('idx_day_gan'), 'guali_time', ['day_gan'], unique=False)
    op.alter_column('guali_time', 'xun_kong',
               existing_type=mysql.VARCHAR(length=4),
               comment='旬空',
               existing_nullable=True)
    op.alter_column('guali_time', 'day_zhi',
               existing_type=mysql.VARCHAR(length=2),
               comment='日支',
               existing_nullable=True)
    op.alter_column('guali_time', 'day_gan',
               existing_type=mysql.VARCHAR(length=2),
               comment='日干',
               existing_nullable=True)
    op.alter_column('guali_time', 'day_pillar',
               existing_type=mysql.VARCHAR(length=4),
               comment='日柱',
               existing_nullable=True)
    op.alter_column('guali_time', 'month_zhi',
               existing_type=mysql.VARCHAR(length=2),
               comment='月支',
               existing_nullable=True)
    op.alter_column('guali_time', 'month_gan',
               existing_type=mysql.VARCHAR(length=2),
               comment='月干',
               existing_nullable=True)
    op.alter_column('guali_time', 'month_pillar',
               existing_type=mysql.VARCHAR(length=4),
               comment='月柱',
               existing_nullable=True)
    op.alter_column('guali_time', 'year_zhi',
               existing_type=mysql.VARCHAR(length=2),
               comment='年支',
               existing_nullable=True)
    op.alter_column('guali_time', 'year_gan',
               existing_type=mysql.VARCHAR(length=2),
               comment='年干',
               existing_nullable=True)
    op.alter_column('guali_time', 'year_pillar',
               existing_type=mysql.VARCHAR(length=4),
               comment='年柱',
               existing_nullable=True)
    op.alter_column('guali_time', 'guali_id',
               existing_type=mysql.INTEGER(),
               comment='关联卦例ID',
               existing_nullable=False)
    op.create_table_comment(
        'guali_tag',
        '卦例-标签关联表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('guali_tag_ibfk_1', 'guali_tag', type_='foreignkey')
    op.drop_constraint('guali_tag_ibfk_1', 'guali_tag', type_='foreignkey')
    op.create_foreign_key(op.f('guali_tag_ibfk_1'), 'guali_tag', 'guali', ['guali_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('guali_tag_ibfk_2'), 'guali_tag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'guali_shensha',
        '神煞扩展表（1行/卦例，37字段）',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('guali_shensha_ibfk_1', 'guali_shensha', type_='foreignkey')
    op.create_foreign_key(op.f('guali_shensha_ibfk_1'), 'guali_shensha', 'guali', ['guali_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('uk_guali_id'), 'guali_shensha', ['guali_id'], unique=True)
    op.create_index(op.f('idx_zai_sha'), 'guali_shensha', ['zai_sha'], unique=False)
    op.create_index(op.f('idx_yi_ma'), 'guali_shensha', ['yi_ma'], unique=False)
    op.create_index(op.f('idx_yang_ren'), 'guali_shensha', ['yang_ren'], unique=False)
    op.create_index(op.f('idx_tao_hua'), 'guali_shensha', ['tao_hua'], unique=False)
    op.create_index(op.f('idx_shensha_guali_id'), 'guali_shensha', ['guali_id'], unique=False)
    op.create_index(op.f('idx_jie_sha'), 'guali_shensha', ['jie_sha'], unique=False)
    op.create_index(op.f('idx_gan_lu'), 'guali_shensha', ['gan_lu'], unique=False)
    op.alter_column('guali_shensha', 'zhi_dai_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_is_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_dai_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_is_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_dai_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_is_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_dai_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_is_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_dai_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_is_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_dai_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zhi_is_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_dai_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_is_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_dai_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_is_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_dai_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_is_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_dai_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_is_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_dai_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_is_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_dai_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'ben_is_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_dai_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_is_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_dai_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_is_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_dai_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_is_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_dai_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_is_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_dai_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_is_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_dai_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'zengshan_is_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_dai_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_is_jiesha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是劫煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_dai_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_is_zaisha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是灾煞的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_dai_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_is_taohua',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是桃花的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_dai_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_is_yangren',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是羊刃的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_dai_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_is_yima',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是驿马的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_dai_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='带干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'yimao_is_ganlu',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               comment='是干禄的爻位',
               existing_server_default=sa.text("''"))
    op.alter_column('guali_shensha', 'jie_sha',
               existing_type=mysql.VARCHAR(length=2),
               comment='劫煞地支',
               existing_nullable=True)
    op.alter_column('guali_shensha', 'zai_sha',
               existing_type=mysql.VARCHAR(length=2),
               comment='灾煞地支',
               existing_nullable=True)
    op.alter_column('guali_shensha', 'tao_hua',
               existing_type=mysql.VARCHAR(length=2),
               comment='桃花地支',
               existing_nullable=True)
    op.alter_column('guali_shensha', 'yang_ren',
               existing_type=mysql.VARCHAR(length=2),
               comment='羊刃地支',
               existing_nullable=True)
    op.alter_column('guali_shensha', 'yi_ma',
               existing_type=mysql.VARCHAR(length=2),
               comment='驿马地支',
               existing_nullable=True)
    op.alter_column('guali_shensha', 'gan_lu',
               existing_type=mysql.VARCHAR(length=2),
               comment='干禄地支',
               existing_nullable=True)
    op.alter_column('guali_shensha', 'guali_id',
               existing_type=mysql.INTEGER(),
               comment='关联卦例ID',
               existing_nullable=False)
    op.create_table_comment(
        'guali_gua',
        '卦类扩展表（1行/卦例，14字段）',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('guali_gua_ibfk_1', 'guali_gua', type_='foreignkey')
    op.create_foreign_key(op.f('guali_gua_ibfk_1'), 'guali_gua', 'guali', ['guali_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('uk_guali_id'), 'guali_gua', ['guali_id'], unique=True)
    op.create_index(op.f('idx_zhi_special_type'), 'guali_gua', ['zhi_special_type'], unique=False)
    op.create_index(op.f('idx_zhi_palace_type'), 'guali_gua', ['zhi_palace_type'], unique=False)
    op.create_index(op.f('idx_zhi_palace'), 'guali_gua', ['zhi_palace'], unique=False)
    op.create_index(op.f('idx_gua_guali_id'), 'guali_gua', ['guali_id'], unique=False)
    op.create_index(op.f('idx_fan_yin'), 'guali_gua', ['fan_yin_yimao', 'fan_yin_yaobian', 'fu_yin'], unique=False)
    op.create_index(op.f('idx_ben_special_type'), 'guali_gua', ['ben_special_type'], unique=False)
    op.create_index(op.f('idx_ben_palace_type'), 'guali_gua', ['ben_palace_type'], unique=False)
    op.create_index(op.f('idx_ben_palace'), 'guali_gua', ['ben_palace'], unique=False)
    op.alter_column('guali_gua', 'fu_yin',
               existing_type=mysql.VARCHAR(length=4),
               comment='伏吟',
               existing_nullable=True)
    op.alter_column('guali_gua', 'fan_yin_yaobian',
               existing_type=mysql.VARCHAR(length=4),
               comment='爻变反吟',
               existing_nullable=True)
    op.alter_column('guali_gua', 'fan_yin_yimao',
               existing_type=mysql.VARCHAR(length=4),
               comment='易冒反吟',
               existing_nullable=True)
    op.alter_column('guali_gua', 'zhi_special_type',
               existing_type=mysql.VARCHAR(length=10),
               comment='之卦特殊类型',
               existing_nullable=True)
    op.alter_column('guali_gua', 'zhi_palace_type',
               existing_type=mysql.VARCHAR(length=10),
               comment='之卦宫位',
               existing_nullable=True)
    op.alter_column('guali_gua', 'zhi_palace',
               existing_type=mysql.VARCHAR(length=10),
               comment='之卦卦宫',
               existing_nullable=True)
    op.alter_column('guali_gua', 'zhi_outer_code',
               existing_type=mysql.VARCHAR(length=3),
               comment='之卦外卦代码',
               existing_nullable=True)
    op.alter_column('guali_gua', 'zhi_inner_code',
               existing_type=mysql.VARCHAR(length=3),
               comment='之卦内卦代码',
               existing_nullable=True)
    op.alter_column('guali_gua', 'ben_special_type',
               existing_type=mysql.VARCHAR(length=10),
               comment='本卦特殊类型',
               existing_nullable=True)
    op.alter_column('guali_gua', 'ben_palace_type',
               existing_type=mysql.VARCHAR(length=10),
               comment='本卦宫位',
               existing_nullable=True)
    op.alter_column('guali_gua', 'ben_palace',
               existing_type=mysql.VARCHAR(length=10),
               comment='本卦卦宫',
               existing_nullable=True)
    op.alter_column('guali_gua', 'ben_outer_code',
               existing_type=mysql.VARCHAR(length=3),
               comment='本卦外卦代码',
               existing_nullable=True)
    op.alter_column('guali_gua', 'ben_inner_code',
               existing_type=mysql.VARCHAR(length=3),
               comment='本卦内卦代码',
               existing_nullable=True)
    op.alter_column('guali_gua', 'guali_id',
               existing_type=mysql.INTEGER(),
               comment='关联卦例ID',
               existing_nullable=False)
    op.create_table_comment(
        'guali',
        '卦例主表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_zhi_code'), 'guali', ['zhi_code'], unique=False)
    op.create_index(op.f('idx_zhanwen_shiyou'), 'guali', ['zhanwen_shiyou'], unique=False, mysql_length={'zhanwen_shiyou': 100})
    op.create_index(op.f('idx_ben_code'), 'guali', ['ben_code'], unique=False)
    op.alter_column('guali', 'zhi_code',
               existing_type=mysql.VARCHAR(length=6),
               comment='之卦代码',
               existing_nullable=False,
               existing_server_default=sa.text("'000000'"))
    op.alter_column('guali', 'yao_bian_code',
               existing_type=mysql.VARCHAR(length=6),
               comment='爻变代码',
               existing_nullable=False,
               existing_server_default=sa.text("'000000'"))
    op.alter_column('guali', 'ben_code',
               existing_type=mysql.VARCHAR(length=6),
               comment='本卦代码',
               existing_nullable=False)
    op.alter_column('guali', 'zhanduan',
               existing_type=mysql.TEXT(),
               comment='占断内容',
               existing_nullable=True)
    op.alter_column('guali', 'zhanwen_shiyou',
               existing_type=mysql.TEXT(),
               comment='占问事由',
               existing_nullable=True)
    op.alter_column('guali', 'zhanwen_time',
               existing_type=mysql.DATETIME(),
               comment='占问时间',
               existing_nullable=False)
    op.create_table_comment(
        'guaci',
        '卦爻辞表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('guaci', 'yong',
               existing_type=mysql.JSON(),
               comment='用九/用六（仅乾坤二卦）',
               existing_nullable=True)
    op.alter_column('guaci', 'wenyan',
               existing_type=mysql.TEXT(),
               comment='文言（仅乾坤二卦）',
               existing_nullable=True)
    op.alter_column('guaci', 'yao_ci',
               existing_type=mysql.JSON(),
               comment='爻辞（JSON格式）',
               existing_nullable=True)
    op.alter_column('guaci', 'xiang_zhuan',
               existing_type=mysql.TEXT(),
               comment='象传',
               existing_nullable=True)
    op.alter_column('guaci', 'tuan_zhuan',
               existing_type=mysql.TEXT(),
               comment='彖传',
               existing_nullable=True)
    op.alter_column('guaci', 'gua_ci',
               existing_type=mysql.TEXT(),
               comment='卦辞',
               existing_nullable=True)
    op.alter_column('guaci', 'code',
               existing_type=mysql.VARCHAR(length=6),
               comment='卦代码',
               existing_nullable=False)
    op.create_table_comment(
        'futures_minute_kline',
        '期货分钟K线表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('futures_minute_kline_ibfk_1', 'futures_minute_kline', type_='foreignkey')
    op.create_foreign_key(op.f('futures_minute_kline_ibfk_1'), 'futures_minute_kline', 'futures_info', ['futures_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_futures_time'), 'futures_minute_kline', ['futures_id', 'trade_time'], unique=False)
    op.alter_column('futures_minute_kline', 'volume',
               existing_type=mysql.BIGINT(),
               comment='成交量',
               existing_nullable=True)
    op.alter_column('futures_minute_kline', 'close_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='收盘价',
               existing_nullable=True)
    op.alter_column('futures_minute_kline', 'low_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='最低价',
               existing_nullable=True)
    op.alter_column('futures_minute_kline', 'high_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='最高价',
               existing_nullable=True)
    op.alter_column('futures_minute_kline', 'open_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='开盘价',
               existing_nullable=True)
    op.alter_column('futures_minute_kline', 'trade_time',
               existing_type=mysql.DATETIME(),
               comment='交易时间（精确到分钟，含夜盘跨天时间）',
               existing_nullable=False)
    op.alter_column('futures_minute_kline', 'futures_id',
               existing_type=mysql.INTEGER(),
               comment='期货ID',
               existing_nullable=False)
    op.create_table_comment(
        'futures_info',
        '期货信息表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('futures_info_ibfk_1', 'futures_info', type_='foreignkey')
    op.create_foreign_key(op.f('futures_info_ibfk_1'), 'futures_info', 'tag', ['tag_id'], ['id'], ondelete='SET NULL')
    op.alter_column('futures_info', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('futures_info', 'tag_id',
               existing_type=mysql.INTEGER(),
               comment='关联标签ID',
               existing_nullable=True)
    op.alter_column('futures_info', 'data_source',
               existing_type=mysql.VARCHAR(length=20),
               comment='数据来源',
               existing_nullable=True)
    op.alter_column('futures_info', 'night_session',
               existing_type=mysql.VARCHAR(length=10),
               comment='交易时段类型：无/短(23:00)/长(02:30)/外盘(24h)',
               existing_nullable=True)
    op.alter_column('futures_info', 'exchange',
               existing_type=mysql.VARCHAR(length=20),
               comment='交易所',
               existing_nullable=True)
    op.alter_column('futures_info', 'futures_name',
               existing_type=mysql.VARCHAR(length=50),
               comment='期货名称',
               existing_nullable=False)
    op.alter_column('futures_info', 'futures_code',
               existing_type=mysql.VARCHAR(length=20),
               comment='期货代码',
               existing_nullable=False)
    op.create_table_comment(
        'bagong_gua',
        '八宫卦序表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('bagong_gua', 'palace_type',
               existing_type=mysql.VARCHAR(length=10),
               comment='宫位类型',
               existing_nullable=False)
    op.alter_column('bagong_gua', 'element',
               existing_type=mysql.VARCHAR(length=5),
               comment='五行',
               existing_nullable=False)
    op.alter_column('bagong_gua', 'palace',
               existing_type=mysql.VARCHAR(length=10),
               comment='卦宫',
               existing_nullable=False)
    op.alter_column('bagong_gua', 'name',
               existing_type=mysql.VARCHAR(length=20),
               comment='卦名',
               existing_nullable=False)
    op.alter_column('bagong_gua', 'code',
               existing_type=mysql.VARCHAR(length=6),
               comment='卦代码',
               existing_nullable=False)
    # ### end Alembic commands ###
